# Generated by Django 4.0.3 on 2022-05-02 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0005_avatar_turnos_delete_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='animales',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppVet.clientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animales',
            name='link',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnos',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppVet.clientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnos',
            name='link',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnos',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='hora',
            field=models.DateTimeField(),
        ),
    ]
