# Generated by Django 4.0.3 on 2022-05-04 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0005_avatar_turnos_delete_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='apellido')),
                ('comentarios', models.CharField(max_length=20, verbose_name='comentario')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='animales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppVet.animales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='link',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnos',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='hora',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
