# Generated by Django 4.0.3 on 2022-05-02 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0006_animales_cliente_animales_link_turnos_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animales',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='animales',
            name='link',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppVet.animales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='link',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
