# Generated by Django 4.0.3 on 2022-05-04 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0006_comentarios_alter_turnos_dia_alter_turnos_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='animales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppVet.animales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='link',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
