# Generated by Django 4.0.3 on 2022-05-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0008_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppVet.clientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnos',
            name='link',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
